route:
  group_wait: 0s
  group_interval: 30s
  repeat_interval: 30s
  receiver: signal-alert-proxy

receivers:
  # no notifications will be sent to alertmanager
  - name: 'empty-receiver'
  - name: signal-alert-proxy
    webhook_configs:
      - url: http://signal-alert-proxy:8085/alert
        send_resolved: true
